name       : joe
version    : '4.6'
release    : 3
source     :
    - https://sourceforge.net/projects/joe-editor/files/JOE%20sources/joe-4.6/joe-4.6.tar.gz/download : 495a0a61f26404070fe8a719d80406dc7f337623788e445b92a9f6de512ab9de
license    : GPL-2.0-or-later
component  : editor
summary    : Small text editor that can emulate other popular text editors
description: |
    Joe is a simple but powerful text editor. In addition to its default look. It can emulate GNU Emacs, WordStar and Pico. Termcap/Terminfo support allows JOE to use any terminal or terminal emulator. It also supports ANSI terminals.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
